- name: ensure vim is installed
  apt:
    name: vim
    state: latest

- name: link .vim/
  file:
    src: "{{ ansible_env.PWD | dirname }}/.vim"
    path: "{{ ansible_env.HOME }}/.vim"
    state: link

- name: link .vimrc
  file:
    src: "{{ ansible_env.PWD | dirname }}/.vim/.vimrc"
    path: "{{ ansible_env.HOME }}/.vimrc"
    state: link
